const WEAPONS_DATA = [
  // ─── KARA KUVVETLERİ ───
  { id: 1, name: "Altay", branch: "kara", category: "Zırhlı Araç", manufacturer: "BMC", status: "Aktif", year: 2023,
    desc: "Türkiye'nin ilk yerli ana muharebe tankı. 120mm smoothbore top, composite zırh ve aktif koruma sistemi.",
    specs: { ağırlık: "65 ton", mürettebat: "4", hız: "70 km/s", menzil: "450 km", silah: "120mm L/55" },
    icon: "🛡" },
  { id: 2, name: "Kaplan MT", branch: "kara", category: "Zırhlı Araç", manufacturer: "FNSS", status: "Aktif", year: 2022,
    desc: "Orta sınıf yerli tank. Endonezya ve diğer ülkelere ihraç edilen hafif-orta muharebe tankı.",
    specs: { ağırlık: "35 ton", mürettebat: "3", hız: "70 km/s", menzil: "450 km", silah: "105mm Cockerill" },
    icon: "🛡" },
  { id: 3, name: "PARS IV 8x8", branch: "kara", category: "Zırhlı Araç", manufacturer: "FNSS", status: "Aktif", year: 2021,
    desc: "8 tekerlekli zırhlı muharebe aracı. Modüler yapısı ile farklı görev konfigürasyonlarına uyarlanabilir.",
    specs: { ağırlık: "26 ton", mürettebat: "3+9", hız: "100 km/s", menzil: "800 km", silah: "30mm otomatik top" },
    icon: "🚛" },
  { id: 4, name: "PARS Scout", branch: "kara", category: "Zırhlı Araç", manufacturer: "FNSS", status: "Aktif", year: 2020,
    desc: "6x6 keşif aracı. Yüksek mobilite ve gelişmiş sensör paketi ile keşif görevleri.",
    specs: { ağırlık: "15 ton", mürettebat: "3+4", hız: "110 km/s", menzil: "700 km", silah: "12.7mm makineli tüfek" },
    icon: "🔭" },
  { id: 5, name: "Kirpi II", branch: "kara", category: "Zırhlı Araç", manufacturer: "BMC", status: "Aktif", year: 2019,
    desc: "Mayına ve el yapımı patlayıcılara karşı korumalı mayın korumalı araç (MRAP).",
    specs: { ağırlık: "16 ton", mürettebat: "2+13", hız: "100 km/s", menzil: "600 km", silah: "12.7mm" },
    icon: "🚐" },
  { id: 6, name: "Vuran", branch: "kara", category: "Zırhlı Araç", manufacturer: "BMC", status: "Aktif", year: 2020,
    desc: "4x4 zırhlı muharebe aracı. Hafif zırhlı birlikler için tasarlanmış.",
    specs: { ağırlık: "12 ton", mürettebat: "2+8", hız: "110 km/s", menzil: "600 km", silah: "12.7mm" },
    icon: "🚐" },
  { id: 7, name: "Ejder Yalçın", branch: "kara", category: "Zırhlı Araç", manufacturer: "Nurol Makina", status: "Aktif", year: 2017,
    desc: "4x4 zırhlı muharebe aracı. Özel harekat ve sınır güvenliği görevleri için.",
    specs: { ağırlık: "18 ton", mürettebat: "2+9", hız: "110 km/s", menzil: "700 km", silah: "12.7mm" },
    icon: "🚐" },
  { id: 8, name: "ACV-15", branch: "kara", category: "Zırhlı Araç", manufacturer: "FNSS", status: "Aktif", year: 1992,
    desc: "Zırhlı personel taşıyıcı. Türk ordusunun en yaygın zırhlı araçlarından biri.",
    specs: { ağırlık: "14 ton", mürettebat: "3+10", hız: "65 km/s", menzil: "490 km", silah: "25mm top" },
    icon: "🚛" },
  { id: 9, name: "Tulpar", branch: "kara", category: "Zırhlı Araç", manufacturer: "Otokar", status: "Aktif", year: 2016,
    desc: "Zırhlı personel taşıyıcı. Modüler zırh sistemi ve yüksek koruma seviyesi.",
    specs: { ağırlık: "32 ton", mürettebat: "3+12", hız: "70 km/s", menzil: "600 km", silah: "30mm" },
    icon: "🚛" },
  { id: 10, name: "Arma 8x8", branch: "kara", category: "Zırhlı Araç", manufacturer: "Otokar", status: "Aktif", year: 2020,
    desc: "8 tekerlekli zırhlı muharebe aracı. Yüksek ateş gücü ve koruma dengesi.",
    specs: { ağırlık: "28 ton", mürettebat: "3+8", hız: "105 km/s", menzil: "800 km", silah: "30mm" },
    icon: "🚛" },
  { id: 11, name: "T-155 Fırtına", branch: "kara", category: "Topçu", manufacturer: "BMC", status: "Aktif", year: 2002,
    desc: "155mm kundağı motorlu obüs. 40 km menzile sahip kendi kendine tahrikli topçu sistemi.",
    specs: { kalibre: "155mm", menzil: "40 km", hız: "60 km/s", mürettebat: "5", atış_hızı: "3 mermi/dk" },
    icon: "💥" },
  { id: 12, name: "Boran 105", branch: "kara", category: "Topçu", manufacturer: "MKE", status: "Aktif", year: 2018,
    desc: "105mm hafif obüs. Hava indirme birlikleri ve dağ birlikleri için tasarlanmış.",
    specs: { kalibre: "105mm", menzil: "17 km", ağırlık: "1.8 ton", mürettebat: "5", taşınabilir: "Helikopter" },
    icon: "💥" },
  { id: 13, name: "Panter", branch: "kara", category: "Topçu", manufacturer: "MKE", status: "Aktif", year: 2002,
    desc: "155mm çekili obüs. T-155 Fırtına ile aynı mühimmatı kullanan çekili top sistemi.",
    specs: { kalibre: "155mm", menzil: "40 km", ağırlık: "18 ton", mürettebat: "8", çekici: "Kamyon" },
    icon: "💥" },
  { id: 14, name: "Bora", branch: "kara", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2017,
    desc: "Taktik balistik füze. 280 km menzile sahip yerli balistik füze sistemi.",
    specs: { menzil: "280 km", ağırlık: "2.5 ton", savaş_başı: "470 kg", doğruluk: "CEP <10m", platform: "Mobil" },
    icon: "🚀" },
  { id: 15, name: "Khan", branch: "kara", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2022,
    desc: "Güdümlü roket sistemi. Bora'nın geliştirilmiş versiyonu, 80 km menzil.",
    specs: { menzil: "80 km", çap: "610mm", savaş_başı: "470 kg", platform: "Mobil", doğruluk: "GPS/INS" },
    icon: "🚀" },
  { id: 16, name: "T-122 ÇNRA", branch: "kara", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 1997,
    desc: "122mm çok namlulu roketatar. 40 km menzile sahip çoklu roketatar sistemi.",
    specs: { kalibre: "122mm", menzil: "40 km", namlu: "40", platform: "Kamyon", atış_hızı: "40 roket/80sn" },
    icon: "🚀" },
  { id: 17, name: "T-300 Kasırga", branch: "kara", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2000,
    desc: "300mm çok namlulu roketatar. 100 km menzile sahip ağır roketatar sistemi.",
    specs: { kalibre: "300mm", menzil: "100 km", namlu: "4", platform: "Kamyon", savaş_başı: "150 kg" },
    icon: "🚀" },
  { id: 18, name: "Kaplan-10", branch: "kara", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2019,
    desc: "Anti-tank füze sistemi. Uzaktan kumandalı anti-tank füze platformu.",
    specs: { menzil: "4 km", tip: "Anti-tank", platform: "Modüler", güdüm: "Lazer/IR" },
    icon: "🎯" },
  { id: 19, name: "OMTAS", branch: "kara", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2016,
    desc: "Orta menzilli anti-tank füze sistemi. Piyade birlikleri için taşınabilir ATGM.",
    specs: { menzil: "4 km", tip: "Anti-tank", ağırlık: "35 kg", güdüm: "IR", savaş_başı: "Tandem HEAT" },
    icon: "🎯" },
  { id: 20, name: "UMTAS", branch: "kara", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2012,
    desc: "Uzun menzilli anti-tank füze. Helikopter ve kara platformları için lazer güdümlü ATGM.",
    specs: { menzil: "8 km", tip: "Anti-tank", güdüm: "Lazer", platform: "Helikopter/Kara" },
    icon: "🎯" },
  { id: 21, name: "Cirit", branch: "kara", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2010,
    desc: "Lazer güdümlü 70mm roket. Helikopter ve kara platformları için hassas mühimmat.",
    specs: { kalibre: "70mm", menzil: "8 km", güdüm: "Lazer", platform: "Çoklu" },
    icon: "🎯" },
  { id: 22, name: "HİSAR-A", branch: "kara", category: "Hava Savunma", manufacturer: "Roketsan/Aselsan", status: "Aktif", year: 2021,
    desc: "Alçak irtifa hava savunma füzesi. 15 km menzile sahip yerli hava savunma sistemi.",
    specs: { menzil: "15 km", irtifa: "10 km", platform: "Mobil", hedef: "Uçak/Helikopter/İHA" },
    icon: "🛡" },
  { id: 23, name: "HİSAR-O", branch: "kara", category: "Hava Savunma", manufacturer: "Roketsan/Aselsan", status: "Aktif", year: 2021,
    desc: "Orta irtifa hava savunma füzesi. 25 km menzile sahip katmanlı hava savunma.",
    specs: { menzil: "25 km", irtifa: "15 km", platform: "Mobil", hedef: "Uçak/Füze/İHA" },
    icon: "🛡" },
  { id: 24, name: "Korkut", branch: "kara", category: "Hava Savunma", manufacturer: "Aselsan", status: "Aktif", year: 2016,
    desc: "35mm çift namlulu hava savunma topu. İHA ve düşük irtifa tehditlere karşı.",
    specs: { kalibre: "35mm", menzil: "4 km", irtifa: "3 km", atış_hızı: "1100 mermi/dk" },
    icon: "🔫" },
  { id: 25, name: "PARS İHA", branch: "kara", category: "İHA", manufacturer: "Aselsan", status: "Aktif", year: 2020,
    desc: "Kamikaze İHA sistemi. Otonom hedef tespiti ve imha kabiliyeti.",
    specs: { menzil: "15 km", irtifa: "3 km", süre: "30 dk", savaş_başı: "3 kg", tip: "Kamikaze" },
    icon: "🛸" },
  { id: 26, name: "Kargu-2", branch: "kara", category: "İHA", manufacturer: "STM", status: "Aktif", year: 2020,
    desc: "Otonom kamikaze İHA. Yapay zeka destekli hedef tanıma ve saldırı.",
    specs: { menzil: "10 km", irtifa: "4 km", süre: "30 dk", savaş_başı: "1.4 kg", tip: "Kamikaze" },
    icon: "🛸" },
  { id: 27, name: "Alpagu", branch: "kara", category: "İHA", manufacturer: "STM", status: "Aktif", year: 2021,
    desc: "Tek kullanımlık saldırı İHA'sı. Piyade birlikleri için taşınabilir kamikaze drone.",
    specs: { menzil: "5 km", irtifa: "2 km", süre: "10 dk", savaş_başı: "0.5 kg", tip: "Kamikaze" },
    icon: "🛸" },
  { id: 28, name: "Songar", branch: "kara", category: "İHA", manufacturer: "Asisguard", status: "Aktif", year: 2019,
    desc: "Silahlı mini İHA. 200g'a kadar mühimmat taşıyabilen quadrotor platform.",
    specs: { menzil: "10 km", irtifa: "3 km", süre: "30 dk", mühimmat: "200g", tip: "Silahlı" },
    icon: "🛸" },
  { id: 29, name: "MPT-76", branch: "kara", category: "Silah", manufacturer: "MKE", status: "Aktif", year: 2014,
    desc: "Milli piyade tüfeği. 7.62x51mm NATO standartında yerli piyade silahı.",
    specs: { kalibre: "7.62x51mm", menzil: "600m", ağırlık: "4.1 kg", şarjör: "20 mermi", tip: "Otomatik" },
    icon: "🔫" },
  { id: 30, name: "MPT-55", branch: "kara", category: "Silah", manufacturer: "MKE", status: "Aktif", year: 2016,
    desc: "5.56mm milli piyade tüfeği. Hafif piyade birlikleri için standart silah.",
    specs: { kalibre: "5.56x45mm", menzil: "500m", ağırlık: "3.5 kg", şarjör: "30 mermi", tip: "Otomatik" },
    icon: "🔫" },
  { id: 31, name: "JNG-90", branch: "kara", category: "Silah", manufacturer: "MKE", status: "Aktif", year: 1990,
    desc: "12.7mm ağır makineli tüfek. Zırhlı araçlar ve sabit mevzi savunması için.",
    specs: { kalibre: "12.7x99mm", menzil: "1800m", ağırlık: "38 kg", atış_hızı: "600 mermi/dk" },
    icon: "🔫" },
  { id: 32, name: "SARP", branch: "kara", category: "Silah Sistemi", manufacturer: "Aselsan", status: "Aktif", year: 2015,
    desc: "Uzaktan komutalı silah istasyonu. Zırhlı araçlar için stabil silah platformu.",
    specs: { silah: "7.62-12.7mm", güdüm: "Otomatik", sensör: "Termal/Gündüz", platform: "Araç üstü" },
    icon: "🔫" },
  { id: 33, name: "STAMP", branch: "kara", category: "Silah Sistemi", manufacturer: "Aselsan", status: "Aktif", year: 2018,
    desc: "Stabilize makineli tüfek platformu. Deniz ve kara platformları için RCWS.",
    specs: { silah: "12.7-40mm", güdüm: "Stabilize", sensör: "Multi-spectral", platform: "Modüler" },
    icon: "🔫" },
  { id: 34, name: "MArG 105", branch: "kara", category: "Topçu", manufacturer: "MKE", status: "Aktif", year: 2020,
    desc: "105mm havan topu. Piyade birliklerinin doğrudan destek silahı.",
    specs: { kalibre: "105mm", menzil: "11 km", ağırlık: "585 kg", mürettebat: "5" },
    icon: "💥" },
  { id: 35, name: "NEB", branch: "kara", category: "Mühimmat", manufacturer: "MKE", status: "Aktif", year: 2019,
    desc: "Nüfuz edici bomba. Bunker ve sağlam hedeflere karşı yerli penetrasyon bombası.",
    specs: { ağırlık: "870 kg", penetrasyon: "2.4m beton", platform: "Hava", tip: "Guided" },
    icon: "💣" },
  { id: 36, name: "SOM-J", branch: "kara", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2018,
    desc: "Stand-off mühimmat. F-35 dahil savaş uçakları için yerli seyir füzesi.",
    specs: { menzil: "275 km", savaş_başı: "230 kg", güdüm: "GPS/INS/IIR", platform: "Hava" },
    icon: "🚀" },
  { id: 37, name: "TOGAN", branch: "kara", category: "İHA", manufacturer: "Aselsan", status: "Aktif", year: 2021,
    desc: "El bombası atabilen mini İHA. Piyade birlikleri için loitering munition.",
    specs: { menzil: "5 km", irtifa: "500m", süre: "15 dk", mühimmat: "El bombası", tip: "Kamikaze" },
    icon: "🛸" },
  { id: 38, name: "Alkar", branch: "kara", category: "Topçu", manufacturer: "Aselsan", status: "Aktif", year: 2021,
    desc: "120mm akıllı havan mermisi. GPS güdümlü hassas havan mühimmatı.",
    specs: { kalibre: "120mm", menzil: "8 km", doğruluk: "CEP <10m", güdüm: "GPS/INS" },
    icon: "💥" },
  { id: 39, name: "Serhat", branch: "kara", category: "Radar", manufacturer: "Aselsan", status: "Aktif", year: 2020,
    desc: "Karadan karaya radar. Sınır güvenliği ve saha gözetleme radar sistemi.",
    specs: { menzil: "40 km", tip: "3D Radar", platform: "Mobil", frekans: "X-Band" },
    icon: "📡" },
  { id: 40, name: "Koral", branch: "kara", category: "Elektronik Harp", manufacturer: "Aselsan", status: "Aktif", year: 2016,
    desc: "Kara tabanlı elektronik harp sistemi. Radar karıştırma ve sinyal istihbaratı.",
    specs: { menzil: "200 km", tip: "EW/ESM", platform: "Mobil", hedef: "Radar/İletişim" },
    icon: "📡" },
  { id: 41, name: "I-DER", branch: "kara", category: "Elektronik Harp", manufacturer: "Aselsan", status: "Aktif", year: 2019,
    desc: "İHA karıştırma sistemi. Düşman İHA'larını etkisiz hale getiren EW sistemi.",
    specs: { menzil: "25 km", tip: "Anti-Drone EW", platform: "Mobil/Sabit" },
    icon: "📡" },
  { id: 42, name: "ZMA", branch: "kara", category: "Zırhlı Araç", manufacturer: "FNSS", status: "Aktif", year: 1998,
    desc: "Zırhlı muharebe aracı. M113 platformu üzerine geliştirilmiş zırhlı araç.",
    specs: { ağırlık: "14 ton", mürettebat: "3+8", hız: "66 km/s", silah: "25mm top" },
    icon: "🚛" },
  { id: 43, name: "Bozok", branch: "kara", category: "Füze", manufacturer: "Roketsan", status: "Geliştirme", year: 2024,
    desc: "Mini füze sistemi. İHA'lardan atılabilen hafif hassas güdümlü mühimmat.",
    specs: { menzil: "20 km", ağırlık: "16 kg", güdüm: "Lazer/GPS", platform: "İHA" },
    icon: "🎯" },
  { id: 44, name: "MZK", branch: "kara", category: "Zırhlı Araç", manufacturer: "BMC", status: "Aktif", year: 2018,
    desc: "Mayın korumalı kamyon. Lojistik konvoyları için mayın korumalı araç.",
    specs: { ağırlık: "15 ton", kapasite: "5 ton", hız: "90 km/s", koruma: "MRAP" },
    icon: "🚐" },
  { id: 45, name: "TOSUN", branch: "kara", category: "Zırhlı Araç", manufacturer: "BMC", status: "Aktif", year: 2020,
    desc: "Ağır zırhlı lojistik aracı. Tehlikeli bölgelerde lojistik destek.",
    specs: { ağırlık: "20 ton", kapasite: "8 ton", hız: "80 km/s", koruma: "MRAP Level 2" },
    icon: "🚐" },
  { id: 46, name: "S-400 Entegrasyon", branch: "kara", category: "Hava Savunma", manufacturer: "Aselsan", status: "Aktif", year: 2019,
    desc: "Yerli radar entegrasyonu. S-400 hava savunma sistemi ile entegre yerli radar ağı.",
    specs: { menzil: "400 km", tip: "Entegrasyon", platform: "Sabit/Mobil" },
    icon: "🛡" },
  { id: 47, name: "SİPER", branch: "kara", category: "Hava Savunma", manufacturer: "Aselsan/Roketsan", status: "Geliştirme", year: 2025,
    desc: "Uzun menzilli hava savunma sistemi. 100+ km menzile sahip yerli SAM sistemi.",
    specs: { menzil: "100+ km", irtifa: "30 km", platform: "Mobil", hedef: "Balistik füze/Uçak" },
    icon: "🛡" },
  { id: 48, name: "Gürz", branch: "kara", category: "Silah", manufacturer: "MKE", status: "Aktif", year: 2020,
    desc: "Yerli makineli tüfek. Piyade birlikleri için hafif makineli tüfek.",
    specs: { kalibre: "5.56x45mm", menzil: "800m", ağırlık: "7 kg", şarjör: "200 mermi" },
    icon: "🔫" },

  // ─── HAVA KUVVETLERİ ───
  { id: 49, name: "Bayraktar TB2", branch: "hava", category: "SİHA", manufacturer: "Baykar", status: "Aktif", year: 2014,
    desc: "Taktik silahlı İHA. 27+ ülkeye ihraç edilen, savaşta kanıtlanmış SİHA platformu.",
    specs: { kanat_açıklığı: "12m", menzil: "150 km", irtifa: "7.6 km", süre: "27 saat", mühimmat: "4 MAM-L" },
    icon: "✈" },
  { id: 50, name: "Akıncı", branch: "hava", category: "SİHA", manufacturer: "Baykar", status: "Aktif", year: 2021,
    desc: "Muharip İHA. Çift turboprop motorlu, ağır mühimmat taşıyabilen SİHA.",
    specs: { kanat_açıklığı: "20m", menzil: "300 km", irtifa: "12 km", süre: "24 saat", mühimmat: "1350 kg" },
    icon: "✈" },
  { id: 51, name: "Kızıl Elma", branch: "hava", category: "SİHA", manufacturer: "Baykar", status: "Geliştirme", year: 2024,
    desc: "İnsansız savaş uçağı. Stealth tasarımlı, süpersonik hızda muharip İHA.",
    specs: { kanat_açıklığı: "15m", hız: "Mach 0.9", irtifa: "15 km", mühimmat: "İç silah+füze", tip: "Stealth" },
    icon: "✈" },
  { id: 52, name: "Anka", branch: "hava", category: "İHA", manufacturer: "TAI", status: "Aktif", year: 2013,
    desc: "Orta irtifa uzun süreli İHA. Keşif-gözetleme ve silahlı görevler.",
    specs: { kanat_açıklığı: "17.5m", menzil: "200 km", irtifa: "9 km", süre: "24 saat", mühimmat: "200 kg" },
    icon: "✈" },
  { id: 53, name: "Aksungur", branch: "hava", category: "İHA", manufacturer: "TAI", status: "Aktif", year: 2020,
    desc: "Çift motorlu muharip İHA. Uzun menzil ve ağır yük kapasiteli İHA.",
    specs: { kanat_açıklığı: "24m", menzil: "300 km", irtifa: "12 km", süre: "40 saat", mühimmat: "750 kg" },
    icon: "✈" },
  { id: 54, name: "Anka-3", branch: "hava", category: "SİHA", manufacturer: "TAI", status: "Geliştirme", year: 2023,
    desc: "Flying wing tasarımlı stealth İHA. Düşük radar izi ile derinlik saldırı.",
    specs: { kanat_açıklığı: "17m", hız: "Mach 0.7", irtifa: "12 km", tip: "Stealth", mühimmat: "1200 kg" },
    icon: "✈" },
  { id: 55, name: "T129 ATAK", branch: "hava", category: "Helikopter", manufacturer: "TAI", status: "Aktif", year: 2014,
    desc: "Taktik taarruz helikopteri. Gece/gündüz her türlü hava koşulunda muharebe.",
    specs: { mürettebat: "2", hız: "278 km/s", menzil: "500 km", irtifa: "6 km", silah: "20mm top+füze" },
    icon: "🚁" },
  { id: 56, name: "Gökbey", branch: "hava", category: "Helikopter", manufacturer: "TAI", status: "Aktif", year: 2021,
    desc: "Genel maksat helikopteri. Yerli tasarım 11 ton sınıfı helikopter.",
    specs: { mürettebat: "2", yük: "19 asker", hız: "306 km/s", menzil: "740 km", irtifa: "5.9 km" },
    icon: "🚁" },
  { id: 57, name: "Hürkuş", branch: "hava", category: "Uçak", manufacturer: "TAI", status: "Aktif", year: 2016,
    desc: "Temel eğitim ve hafif taarruz uçağı. Silahlı ve eğitim versiyonları mevcut.",
    specs: { mürettebat: "2", hız: "574 km/s", menzil: "1500 km", irtifa: "11.5 km", silah: "Yer silahları" },
    icon: "✈" },
  { id: 58, name: "Hürjet", branch: "hava", category: "Uçak", manufacturer: "TAI", status: "Geliştirme", year: 2023,
    desc: "Jet eğitim ve hafif taarruz uçağı. F-16'ların yerini alacak eğitim uçağı.",
    specs: { mürettebat: "2", hız: "Mach 1.4", menzil: "2000 km", irtifa: "14.6 km", silah: "Yer silahları" },
    icon: "✈" },
  { id: 59, name: "KAAN (TF-X)", branch: "hava", category: "Uçak", manufacturer: "TAI", status: "Geliştirme", year: 2024,
    desc: "5. nesil savaş uçağı. Stealth, süpersonik, yerli motor ile milli muharip uçak.",
    specs: { mürettebat: "1", hız: "Mach 1.8", menzil: "1100 km", irtifa: "17 km", silah: "İç+Harici" },
    icon: "✈" },
  { id: 60, name: "MMU (HÜRJET)", branch: "hava", category: "Uçak", manufacturer: "TAI", status: "Geliştirme", year: 2025,
    desc: "Milli muharip uçak projesi kapsamında geliştirilen jet platform.",
    specs: { tip: "5. Nesil", hız: "Mach 1.4+", menzil: "2000+ km", motor: "Yerli" },
    icon: "✈" },
  { id: 61, name: "SOM", branch: "hava", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2011,
    desc: "Stand-off mühimmat. Hava-launched seyir füzesi, 250+ km menzil.",
    specs: { menzil: "250 km", savaş_başı: "230 kg", güdüm: "GPS/INS/TV", platform: "F-16/F-4" },
    icon: "🚀" },
  { id: 62, name: "Gökdoğan", branch: "hava", category: "Füze", manufacturer: "TÜBİTAK SAGE", status: "Aktif", year: 2013,
    desc: "Görüş ötesi hava-hava füzesi. BVR kabiliyetli yerli hava-hava füzesi.",
    specs: { menzil: "65 km", tip: "BVR", güdüm: "Aktif radar", platform: "F-16" },
    icon: "🎯" },
  { id: 63, name: "Bozdoğan", branch: "hava", category: "Füze", manufacturer: "TÜBİTAK SAGE", status: "Aktif", year: 2013,
    desc: "Görüş içi hava-hava füzesi. WVR dogfight kabiliyetli yerli füze.",
    specs: { menzil: "25 km", tip: "WVR", güdüm: "IR", platform: "F-16" },
    icon: "🎯" },
  { id: 64, name: "MAM-L", branch: "hava", category: "Mühimmat", manufacturer: "Roketsan", status: "Aktif", year: 2012,
    desc: "Lazer güdümlü mini akıllı mühimmat. SİHA'ların birincil silahı.",
    specs: { ağırlık: "22 kg", menzil: "8 km", savaş_başı: "10 kg", güdüm: "Lazer/SAL" },
    icon: "💣" },
  { id: 65, name: "MAM-C", branch: "hava", category: "Mühimmat", manufacturer: "Roketsan", status: "Aktif", year: 2012,
    desc: "Kompakt lazer güdümlü mühimmat. Hafif hedefler için mini akıllı bomba.",
    specs: { ağırlık: "6.5 kg", menzil: "8 km", savaş_başı: "2.5 kg", güdüm: "Lazer/SAL" },
    icon: "💣" },
  { id: 66, name: "MAM-T", branch: "hava", category: "Mühimmat", manufacturer: "Roketsan", status: "Aktif", year: 2021,
    desc: "Ağır lazer güdümlü mühimmat. Büyük hedefler için ağır akıllı bomba.",
    specs: { ağırlık: "94 kg", menzil: "8 km", savaş_başı: "45 kg", güdüm: "Lazer/SAL" },
    icon: "💣" },
  { id: 67, name: "LGK-82", branch: "hava", category: "Mühimmat", manufacturer: "TÜBİTAK SAGE", status: "Aktif", year: 2010,
    desc: "Lazer güdümlü kit. 500 lb bombayı hassas güdümlü mühimmata dönüştürür.",
    specs: { ağırlık: "230 kg", menzil: "15 km", doğruluk: "CEP <3m", güdüm: "Lazer" },
    icon: "💣" },
  { id: 68, name: "HGK-84", branch: "hava", category: "Mühimmat", manufacturer: "TÜBİTAK SAGE", status: "Aktif", year: 2008,
    desc: "Hassas güdüm kiti. GPS/INS güdümlü 1000 lb bomba kiti.",
    specs: { ağırlık: "450 kg", menzil: "28 km", doğruluk: "CEP <6m", güdüm: "GPS/INS" },
    icon: "💣" },
  { id: 69, name: "KGK-83", branch: "hava", category: "Mühimmat", manufacturer: "TÜBİTAK SAGE", status: "Aktif", year: 2012,
    desc: "Kanatlı güdüm kiti. Uzaktan atım kabiliyeti olan GPS güdümlü kit.",
    specs: { ağırlık: "450 kg", menzil: "110 km", doğruluk: "CEP <10m", güdüm: "GPS/INS" },
    icon: "💣" },
  { id: 70, name: "NEB", branch: "hava", category: "Mühimmat", manufacturer: "TÜBİTAK SAGE", status: "Aktif", year: 2019,
    desc: "Nüfuz edici bomba. Bunker delici yerli penetrasyon bombası.",
    specs: { ağırlık: "870 kg", penetrasyon: "2.4m beton", platform: "F-16" },
    icon: "💣" },
  { id: 71, name: "EHSİM", branch: "hava", category: "Elektronik Harp", manufacturer: "Aselsan", status: "Aktif", year: 2018,
    desc: "Uçak elektronik harp pod'u. F-16 platformları için EW sistemi.",
    specs: { tip: "EW Pod", platform: "F-16", menzil: "200 km", fonksiyon: "ESM/ECM" },
    icon: "📡" },
  { id: 72, name: "ASELFLIR-500", branch: "hava", category: "Sensör", manufacturer: "Aselsan", status: "Aktif", year: 2015,
    desc: "Hedefleme pod'u. Gece/gündüz hedef tespit ve takip sistemi.",
    specs: { tip: "Targeting Pod", sensör: "FLIR/Lazer/TV", platform: "Helikopter/Uçak" },
    icon: "📡" },
  { id: 73, name: "MURAD", branch: "hava", category: "Radar", manufacturer: "Aselsan", status: "Aktif", year: 2020,
    desc: "Aktif elektronik taranmış dizi radar. 4.5/5. nesil uçaklar için AESA radar.",
    specs: { menzil: "200 km", tip: "AESA", hedef: "200+", platform: "KAAN/Hürjet" },
    icon: "📡" },
  { id: 74, name: "EİRS", branch: "hava", category: "Radar", manufacturer: "Aselsan", status: "Aktif", year: 2018,
    desc: "Elektronik istihbarat recever sistemi. Uçak üstü sinyal istihbaratı.",
    specs: { menzil: "400 km", tip: "ESM", platform: "AEW/Uçak" },
    icon: "📡" },
  { id: 75, name: "Barış Kartalı", branch: "hava", category: "AEW", manufacturer: "Aselsan", status: "Aktif", year: 2015,
    desc: "Hava erken ihbar uçağı. B737 platformu üzerinde yerli AEW sistemi.",
    specs: { menzil: "400 km", irtifa: "12 km", hedef: "300+", platform: "B737" },
    icon: "📡" },
  { id: 76, name: "HAVELSAN ADVENT", branch: "hava", category: "Simülasyon", manufacturer: "Havelsan", status: "Aktif", year: 2018,
    desc: "Bütünleşik hava muharebe yönetim sistemi. Hava savunma komuta kontrol.",
    specs: { tip: "C4ISR", kapsam: "Hava Savunma", platform: "Sabit/Mobil" },
    icon: "🖥" },
  { id: 77, name: "Şimşek", branch: "hava", category: "Hedef Uçağı", manufacturer: "TAI", status: "Aktif", year: 2012,
    desc: "Yüksek hızlı hedef uçağı. Hava savunma testleri için hedef drone.",
    specs: { hız: "Mach 0.95", irtifa: "12 km", tip: "Target Drone", platform: "Fırlatma" },
    icon: "✈" },
  { id: 78, name: "Turna", branch: "hava", category: "Hedef Uçağı", manufacturer: "TAI", status: "Aktif", year: 2010,
    desc: "Orta hızlı hedef uçağı. Füze testleri için hedef drone sistemi.",
    specs: { hız: "Mach 0.6", irtifa: "8 km", tip: "Target Drone" },
    icon: "✈" },
  { id: 79, name: "F-16 ÖZGÜR", branch: "hava", category: "Modernizasyon", manufacturer: "TAI/Aselsan", status: "Aktif", year: 2020,
    desc: "F-16 modernizasyon projesi. Yerli aviyonik ve silah entegrasyonu.",
    specs: { platform: "F-16C/D", kapsam: "Aviyonik+Silah", adet: "35+" },
    icon: "✈" },
  { id: 80, name: "TEI TS1400", branch: "hava", category: "Motor", manufacturer: "TEI", status: "Geliştirme", year: 2023,
    desc: "Yerli turboshaft motor. Gökbey ve ATAK helikopterleri için yerli motor.",
    specs: { güç: "1400 shp", tip: "Turboshaft", platform: "Helikopter" },
    icon: "⚙" },
  { id: 81, name: "TEI TF6000", branch: "hava", category: "Motor", manufacturer: "TEI", status: "Geliştirme", year: 2024,
    desc: "Yerli turbofan motor. KAAN ve MMU için milli jet motoru.",
    specs: { itki: "6000 lbf", tip: "Turbofan", platform: "KAAN/Hürjet" },
    icon: "⚙" },
  { id: 82, name: "Mini Akıncı", branch: "hava", category: "SİHA", manufacturer: "Baykar", status: "Geliştirme", year: 2024,
    desc: "Kompakt muharip İHA. Gemi güvertesinden operasyon yapabilen SİHA.",
    specs: { kanat_açıklığı: "8m", menzil: "100 km", irtifa: "5 km", mühimmat: "200 kg" },
    icon: "✈" },
  { id: 83, name: "DIHA", branch: "hava", category: "İHA", manufacturer: "TAI", status: "Aktif", year: 2019,
    desc: "Dikey iniş-kalkış İHA. Deniz platformları ve şehir içi operasyonlar.",
    specs: { menzil: "50 km", irtifa: "3 km", süre: "4 saat", tip: "VTOL" },
    icon: "🛸" },
  { id: 84, name: "BOZOK", branch: "hava", category: "Mühimmat", manufacturer: "Roketsan", status: "Aktif", year: 2022,
    desc: "Mini füze. İHA'lardan atılan hafif hassas güdümlü mühimmat.",
    specs: { ağırlık: "16 kg", menzil: "15 km", güdüm: "Lazer/GPS", platform: "İHA" },
    icon: "🎯" },

  // ─── DENİZ KUVVETLERİ ───
  { id: 85, name: "İSTİF Sınıfı", branch: "deniz", category: "Fırkateyn", manufacturer: "STM", status: "Aktif", year: 2023,
    desc: "MILGEM projesi fırkateyni. 113m, 3000 ton, yerli tasarım savaş gemisi.",
    specs: { uzunluk: "113m", deplasman: "3000t", hız: "29 knot", mürettebat: "125", silah: "76mm+16 VLS" },
    icon: "🚢" },
  { id: 86, name: "ADA Sınıfı", branch: "deniz", category: "Korvet", manufacturer: "STM", status: "Aktif", year: 2011,
    desc: "MILGEM korvet. Türk deniz kuvvetlerinin omurgasını oluşturan korvet sınıfı.",
    specs: { uzunluk: "99m", deplasman: "2400t", hız: "29 knot", mürettebat: "93", silah: "76mm+8 VLS" },
    icon: "🚢" },
  { id: 87, name: "TF-2000", branch: "deniz", category: "Destroyer", manufacturer: "STM", status: "Geliştirme", year: 2027,
    desc: "Hava savunma harbi muhribi. 8000 ton, yerli AESA radar ile hava savunma destroyeri.",
    specs: { uzunluk: "150m", deplasman: "8000t", hız: "30+ knot", silah: "127mm+64 VLS" },
    icon: "🚢" },
  { id: 88, name: "Preveze Sınıfı", branch: "deniz", category: "Denizaltı", manufacturer: "Gölcük Tersanesi", status: "Aktif", year: 1994,
    desc: "209 Tipi denizaltı. Türk tersanelerinde inşa edilen konvansiyonel denizaltı.",
    specs: { uzunluk: "62m", deplasman: "1584t", hız: "22 knot", mürettebat: "57", torpido: "14" },
    icon: "🔱" },
  { id: 89, name: "Gür Sınıfı", branch: "deniz", category: "Denizaltı", manufacturer: "Gölcük Tersanesi", status: "Aktif", year: 2003,
    desc: "209T Tipi denizaltı. AIP olmayan geliştirilmiş Tip 209 denizaltı.",
    specs: { uzunluk: "62m", deplasman: "1584t", hız: "22 knot", mürettebat: "57", torpido: "14" },
    icon: "🔱" },
  { id: 90, name: "Reis Sınıfı", branch: "deniz", category: "Denizaltı", manufacturer: "Gölcük Tersanesi", status: "Geliştirme", year: 2024,
    desc: "Type 214TN AIP denizaltı. Hava bağımsız tahrik sistemli modern denizaltı.",
    specs: { uzunluk: "68m", deplasman: "1850t", hız: "20 knot", mürettebat: "57", AIP: "Var" },
    icon: "🔱" },
  { id: 91, name: "STM500", branch: "deniz", category: "Denizaltı", manufacturer: "STM", status: "Aktif", year: 2019,
    desc: "Mini denizaltı. 500 ton sınıfı, özel kuvvetler ve kıyı savunması için.",
    specs: { uzunluk: "42m", deplasman: "540t", hız: "18 knot", mürettebat: "18", torpido: "4" },
    icon: "🔱" },
  { id: 92, name: "ATMACA", branch: "deniz", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2021,
    desc: "Gemiden gemiye seyir füzesi. 200+ km menzile sahip yerli anti-ship füzesi.",
    specs: { menzil: "220 km", hız: "Mach 0.9", savaş_başı: "220 kg", güdüm: "GPS/INS+Radar" },
    icon: "🚀" },
  { id: 93, name: "Gezgin", branch: "deniz", category: "Füze", manufacturer: "Roketsan", status: "Geliştirme", year: 2025,
    desc: "Deniz-launched seyir füzesi. Uzun menzilli yerli deniz füzesi.",
    specs: { menzil: "1000+ km", savaş_başı: "450 kg", güdüm: "GPS/INS/Terrain", platform: "VLS" },
    icon: "🚀" },
  { id: 94, name: "Zargana", branch: "deniz", category: "Füze", manufacturer: "Roketsan", status: "Aktif", year: 2018,
    desc: "Hafif torpido. Denizaltı ve yüzey gemilerinden atılabilen yerli torpido.",
    specs: { menzil: "15 km", hız: "40 knot", ağırlık: "260 kg", güdüm: "Aktif/Pasif sonar" },
    icon: "🎯" },
  { id: 95, name: "Orka", branch: "deniz", category: "Füze", manufacturer: "Roketsan", status: "Geliştirme", year: 2025,
    desc: "Ağır torpido. Modern denizaltılar için geliştirilen ağır sınıf torpido.",
    specs: { menzil: "50 km", hız: "55 knot", ağırlık: "1200 kg", güdüm: "Wake homing" },
    icon: "🎯" },
  { id: 96, name: "ULAQ", branch: "deniz", category: "İDA", manufacturer: "Ares/Meteksan", status: "Aktif", year: 2021,
    desc: "Silahlı insansız deniz aracı. Uzaktan kumandalı silahlı USV.",
    specs: { uzunluk: "11m", hız: "35 knot", menzil: "400 km", silah: "4 Cirit+2 UMTAS" },
    icon: "🛥" },
  { id: 97, name: "MARLIN", branch: "deniz", category: "İDA", manufacturer: "Aselsan/Sefine", status: "Aktif", year: 2022,
    desc: "Silahlı insansız deniz aracı. Aselsan silah sistemleri ile donatılmış USV.",
    specs: { uzunluk: "15m", hız: "36 knot", menzil: "500 km", silah: "Stabilize silah" },
    icon: "🛥" },
  { id: 98, name: "SİMAV", branch: "deniz", category: "İDA", manufacturer: "STM", status: "Aktif", year: 2021,
    desc: "İnsansız deniz aracı. Keşif, gözetleme ve silahlı görevler.",
    specs: { uzunluk: "11m", hız: "40 knot", menzil: "300 km", tip: "Multi-role USV" },
    icon: "🛥" },
  { id: 99, name: "Hızır", branch: "deniz", category: "İDA", manufacturer: "Yonca-Onuk", status: "Aktif", year: 2020,
    desc: "Hızlı taarruz botu. Özel kuvvetler için hızlı saldırı botu.",
    specs: { uzunluk: "15m", hız: "50+ knot", mürettebat: "12", silah: "12.7mm+Grenade" },
    icon: "🛥" },
  { id: 100, name: "MRTP-33", branch: "deniz", category: "Hücum Botu", manufacturer: "Yonca-Onuk", status: "Aktif", year: 2015,
    desc: "Hızlı hücum botu. 33 knot hızında hücum ve devriye botu.",
    specs: { uzunluk: "33m", hız: "33 knot", mürettebat: "20", silah: "12.7mm" },
    icon: "🛥" },
  { id: 101, name: "MRTP-29", branch: "deniz", category: "Hücum Botu", manufacturer: "Yonca-Onuk", status: "Aktif", year: 2012,
    desc: "Kompakt hücum botu. Kıyı güvenliği ve özel kuvvetler operasyonları.",
    specs: { uzunluk: "29m", hız: "35 knot", mürettebat: "15", silah: "12.7mm" },
    icon: "🛥" },
  { id: 102, name: "Türkiye Sınıfı", branch: "deniz", category: "LHD", manufacturer: "Sedef Tersanesi", status: "Aktif", year: 2023,
    desc: "Çok maksatlı amfibi hücum gemisi. TCG Anadolu, İHA/SİHA taşıyabilen LHD.",
    specs: { uzunluk: "231m", deplasman: "27000t", hız: "21 knot", uçak: "Bayraktar TB3+Helikopter" },
    icon: "🚢" },
  { id: 103, name: "DİMDEG", branch: "deniz", category: "Destek Gemisi", manufacturer: "Sedef Tersanesi", status: "Geliştirme", year: 2026,
    desc: "Deniz muharebe destek gemisi. LHD sınıfı ikinci gemi projesi.",
    specs: { uzunluk: "231m", deplasman: "27000t", tip: "LHD/LPD", uçak: "SİHA+Helikopter" },
    icon: "🚢" },
  { id: 104, name: "DİSTİNY", branch: "deniz", category: "Tanker", manufacturer: "ADİK Tersanesi", status: "Aktif", year: 2020,
    desc: "Filo ikmal ve tanker gemisi. Deniz kuvvetleri lojistik destek gemisi.",
    specs: { uzunluk: "194m", deplasman: "20000t", hız: "18 knot", kapasite: "11000 ton yakıt" },
    icon: "🚢" },
  { id: 105, name: "Barbaros Modernizasyon", branch: "deniz", category: "Modernizasyon", manufacturer: "Aselsan/STM", status: "Aktif", year: 2020,
    desc: "Barbaros sınıfı fırkateyn modernizasyonu. Yerli silah ve sensör entegrasyonu.",
    specs: { adet: "4", kapsam: "Silah+Sensör+EW", platform: "Barbaros sınıfı" },
    icon: "🚢" },
  { id: 106, name: "Gökdeniz", branch: "deniz", category: "Hava Savunma", manufacturer: "Aselsan", status: "Aktif", year: 2020,
    desc: "Gemiler için yakın hava savunma sistemi. 35mm CIWS yerli hava savunma.",
    specs: { kalibre: "35mm", menzil: "4 km", atış_hızı: "1000 mermi/dk", platform: "Gemi" },
    icon: "🛡" },
  { id: 107, name: "YAKAMOS", branch: "deniz", category: "Sonar", manufacturer: "Aselsan", status: "Aktif", year: 2018,
    desc: "Yerli sonar sistemi. Denizaltı ve yüzey gemileri için sonar.",
    specs: { tip: "Hull-mounted sonar", menzil: "20+ km", platform: "Denizaltı/Gemi" },
    icon: "📡" },
  { id: 108, name: "ÇAFRAD", branch: "deniz", category: "Radar", manufacturer: "Aselsan", status: "Aktif", year: 2019,
    desc: "Çok fonksiyonlu radar. MILGEM gemileri için yerli çok fonksiyonlu radar.",
    specs: { menzil: "250 km", tip: "Multi-function", platform: "MILGEM" },
    icon: "📡" },
  { id: 109, name: "NETAŞ GEMİ", branch: "deniz", category: "C4ISR", manufacturer: "Havelsan", status: "Aktif", year: 2018,
    desc: "Gemi muharebe yönetim sistemi. MILGEM gemileri için yerli CMS.",
    specs: { tip: "Combat Management", platform: "MILGEM/İSTİF", kapsam: "Tam entegrasyon" },
    icon: "🖥" },
  { id: 110, name: "Bayraktar TB3", branch: "deniz", category: "SİHA", manufacturer: "Baykar", status: "Geliştirme", year: 2024,
    desc: "Amfibi hücum gemisi SİHA'sı. TCG Anadolu güvertesinden operasyon yapabilen katlanabilir SİHA.",
    specs: { kanat_açıklığı: "14m", menzil: "200 km", irtifa: "9 km", süre: "24 saat", tip: "Katlanabilir" },
    icon: "✈" },
  { id: 111, name: "MİLDEN", branch: "deniz", category: "Denizaltı", manufacturer: "STM/Gölcük", status: "Geliştirme", year: 2030,
    desc: "Milli denizaltı projesi. Tamamen yerli tasarım ve üretim denizaltı.",
    specs: { deplasman: "3000t", AIP: "Yerli", tip: "Attack Submarine", derinlik: "300m+" },
    icon: "🔱" },
  { id: 112, name: "KERİM", branch: "deniz", category: "İDA", manufacturer: "Aselsan", status: "Geliştirme", year: 2025,
    desc: "Otonom mayın avlama aracı. Yapay zeka destekli mayın tespit ve imha USV.",
    specs: { uzunluk: "12m", hız: "25 knot", tip: "MCM USV", sensör: "Sonar+AI" },
    icon: "🛥" },
];

const BRANCH_LABELS = { kara: "Kara", hava: "Hava", deniz: "Deniz" };
const BRANCH_COLORS = { kara: "#c4a35a", hava: "#4a9eff", deniz: "#2dd4bf" };
const STATUS_COLORS = { Aktif: "#22c55e", Geliştirme: "#f59e0b" };
